# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
env:
  UNITY_VERSION: 2019.4.13f1 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: false
      
      - name: Unity Build
        shell: cmd
        run: /%PROGRAMFILES%/Unity/Hub/Editor/$UNITY_VERSION/Editor/Unity -quit -batchmode -projectPath ./ -executeMethod CI.Build -buildTarget StandaloneWindows64
        
      - name: Relese
        run: Copy-Item Build\Live-V.exe D:\unity\Live-V\Build\Live-V${{ github.run_number }}.exe
